// Types for Kinetic's behavior tracking layer.
//
// Behavior tracking records the loop:
//   1. Kinetic recommends a workout for the day
//   2. The user accepts / rejects / modifies / skips it
//   3. The user logs what they actually did (if anything)
//   4. Over time, repeated patterns harden into learned preferences
//
// These two types are the on-disk schema for both halves of that loop.
// They live in their own module so storage helpers, the recommendation
// engine, and any future server-side adapter can all reference them
// without pulling in the rest of the lib graph.
//
// Keep these types explicit (no enums imported from elsewhere) so they
// can be serialised to JSON, sent to the backend, and surfaced in the
// UI without translation.

/**
 * A single recommendation -> response -> outcome record.
 *
 * One entry is created when Kinetic shows the user a recommendation on
 * a given day. The entry is updated in place when the user responds
 * (`userResponse`, `rejectionReason`) and again when the actual workout
 * is logged (`actualWorkout`). Records are immutable across days —
 * `date` keys them to a calendar day, not a session.
 */
export type RecommendationEvent = {
  /** Stable unique id (e.g. uuid). */
  id: string;
  /** ISO calendar date (YYYY-MM-DD) this recommendation applies to. */
  date: string;
  /** Short label for the workout from the original training plan. */
  plannedWorkout: string;
  /** Short label for the workout Kinetic recommended after recalibration. */
  recommendedWorkout: string;
  /** Action surfaced to the user. */
  selectedAction: "proceed" | "modify" | "rest";
  /** Kinetic's confidence in the recommendation. */
  confidence: "low" | "moderate" | "high";
  /** Recovery score at recommendation time (0..1). Optional — not always available. */
  recoveryScore?: number;
  /** Available training minutes for the day from the calendar layer. */
  availableMinutes?: number;
  /**
   * How the user responded. `null` while a recommendation is still
   * pending (e.g. shown but not yet acted on for the day).
   */
  userResponse: "accepted" | "rejected" | "modified" | "skipped" | null;
  /** Free-text reason captured when the user rejects or modifies. */
  rejectionReason?: string;
  /**
   * The session the user actually completed (if any). Populated only
   * after the workout is logged.
   */
  actualWorkout?: {
    completed: boolean;
    distanceMiles?: number;
    durationMinutes?: number;
    /** Subjective effort 1-10. */
    perceivedEffort?: number;
    /** Bounded reflection category; never raw prose. */
    reflectionCategory?:
      | "easier_than_expected"
      | "as_expected"
      | "harder_than_expected";
    /** Bounded reason for a skipped workout; never raw prose. */
    skipReason?: "schedule" | "recovery" | "pain_or_discomfort" | "other";
    note?: string;
  };
  /** Environmental context at recommendation time. */
  context: {
    calendarLoad?: "light" | "moderate" | "heavy";
    sleepStatus?: "below_baseline" | "normal" | "above_baseline";
    recoveryStatus?: "low" | "moderate" | "high";
  };
};

/**
 * A pattern Kinetic has learned about the runner from repeated
 * behavior. Generated by the preference-mining layer, surfaced to the
 * user for confirmation, and consulted by the recommendation engine
 * when scoring future options.
 */
export type LearnedPreference = {
  /** Stable unique id. */
  id: string;
  /** Which axis of the runner's behavior this preference captures. */
  type:
    | "busy_day_preference"
    | "rest_day_preference"
    | "intensity_tolerance"
    | "schedule_preference";
  /** Human-readable description, e.g. "Prefers easy runs on Wednesdays". */
  description: string;
  /** Strength of the underlying signal. */
  confidence: "low" | "moderate" | "high";
  /** True once the user has explicitly confirmed (e.g. via a prompt). */
  userConfirmed: boolean;
  /** ISO timestamp the preference was first inferred. */
  createdAt: string;
};
